#!/bin/bash
        dir=$1
        RESULT=`find $dir -maxdepth 1 -type f | sed 's= =\\\/=g'`
        # declare -a ARRAY        #"man declare" -a option declares an array
        let count=0
        
#	RESULT=`echo $RESULT | sed 's=\\\/= =g'`
#	echo $RESULT
	for FILE in $RESULT
        do
				FILE=`echo $FILE | sed 's=\\\/= =g'`
				cmp "$FILE" "$FILE"
				
                for FILE2 in $RESULT
				do
					FILE2=`echo $FILE2 | sed 's=\\\/= =g'`
				#	echo "FILE2 IS $FILE2"
					difference=$(cmp "$FILE" "$FILE2" 2>&1)
				#	echo "Difference: $difference"
				#	echo $FILE $FILE2
					if  [[  -z  $difference  && "$FILE" != "$FILE2"  ]]
					then
					#	echo $difference
					#	echo 'MATCH'
					#	echo $FILE $FILE2
				
						if [[ $FILE == "${dir}/."* && $FILE2 != "${dir}/."* ]]
						then
							ln -f "$FILE" "$FILE2"
						elif [[ $FILE2 == "${dir}/."* && $FILE != "${dir}/."* ]]
						then
							ln -f "$FILE2" "$FILE"
						elif  [[ "$FILE"<"$FILE2" ]]
						then
							ln -f "$FILE" "$FILE2"
						else
							ln -f "$FILE2" "$FILE"
						fi
					fi	
				done
			#	echo ""
        done
	#	echo "There are $count regular files."
	
#	echo "$RESULT"


	
