echo /usr/bin/akonadi_mailtransport_dummy_resource
ldd /usr/bin/akonadi_mailtransport_dummy_resource
echo /usr/bin/btrace
ldd /usr/bin/btrace
echo /usr/bin/cimcli
ldd /usr/bin/cimcli
echo /usr/bin/cube_sanity
ldd /usr/bin/cube_sanity
echo /usr/bin/docbook2dvi
ldd /usr/bin/docbook2dvi
echo /usr/bin/explode.pyc
ldd /usr/bin/explode.pyc
echo /usr/bin/gencat
ldd /usr/bin/gencat
echo /usr/bin/gpasswd
ldd /usr/bin/gpasswd
echo /usr/bin/gv
ldd /usr/bin/gv
echo /usr/bin/ib_acme
ldd /usr/bin/ib_acme
echo /usr/bin/jobs
ldd /usr/bin/jobs
echo /usr/bin/kmod
ldd /usr/bin/kmod
echo /usr/bin/leaftoppm
ldd /usr/bin/leaftoppm
echo /usr/bin/mailx
ldd /usr/bin/mailx
echo /usr/bin/mtvtoppm
ldd /usr/bin/mtvtoppm
echo /usr/bin/nmtui-connect
ldd /usr/bin/nmtui-connect
echo /usr/bin/padsp
ldd /usr/bin/padsp
echo /usr/bin/patch
ldd /usr/bin/patch
echo /usr/bin/pg_config
ldd /usr/bin/pg_config
echo /usr/bin/pmgenmap
ldd /usr/bin/pmgenmap
echo /usr/bin/pocommentclean
ldd /usr/bin/pocommentclean
echo /usr/bin/ppmtoyuvsplit
ldd /usr/bin/ppmtoyuvsplit
echo /usr/bin/rdoc
ldd /usr/bin/rdoc
echo /usr/bin/rpmverify
ldd /usr/bin/rpmverify
echo /usr/bin/sha512sum
ldd /usr/bin/sha512sum
echo /usr/bin/svnadmin
ldd /usr/bin/svnadmin
echo /usr/bin/thumbpdf
ldd /usr/bin/thumbpdf
echo /usr/bin/viewer.py
ldd /usr/bin/viewer.py
echo /usr/bin/xliff2odf
ldd /usr/bin/xliff2odf
echo /usr/bin/zipdetails
ldd /usr/bin/zipdetails
